### ISSUE TITLE
ImportError: cannot import name 'triton_key' from 'triton.compiler.compiler'

### ISSUE THREAD

**Issue by pepperychocolate** [kijai/ComfyUI-WanVideoWrapper#1506]
My environment is Windows 11 + RTX 5090, ComfyUI v0.3.65.
Triton version: 3.5.0
PyTorch version: 2.8.0+cu128
CUDA version: 12.8
CUDA available: True

Dear experts, which Triton version should be used with PyTorch 2.8.0? Thank you everyone!

<img width="1092" height="535" alt="Image" src="https://github.com/user-attachments/assets/1e9618c6-be43-4faa-aa6a-25adc0c85401" />

**Comment by kijai** [comment]
I would recommend 2.9.0 as it has some torch.compile fixes for Windows, and if you already aren't using the triton-windows, I'd recommend that too:

https://github.com/woct0rdho/triton-windows/releases

**Comment by thejae** [comment]
> I would recommend 2.9.0 as it has some torch.compile fixes for Windows, and if you already aren't using the triton-windows, I'd recommend that too:
> 
> https://github.com/woct0rdho/triton-windows/releases

Thanks for replying to this thread. I running into this issue too and am using `triton-windows` already (i couldn't find the version 2.9.0 from the link you shared but i do have 3.5.0 installed)

**Comment by bihailantian655** [comment]
Note again that Triton 3.5 only works with PyTorch >= 2.9 .

To install Triton 3.5 and prevent breaking with your installed PyTorch when a new version of Triton is released in future, you need to limit the version to be < 3.6:

Note again that Triton 3.4 only works with PyTorch >= 2.8 .

To install Triton 3.4 and prevent breaking with your installed PyTorch when a new version of Triton is released in future, you need to limit the version to be < 3.5:

Note again that Triton 3.3 only works with PyTorch >= 2.7, and Triton 3.2 only works with PyTorch >= 2.6 .

To install Triton 3.3 and prevent breaking with your installed PyTorch when a new version of Triton is released in future, you need to limit the version to be < 3.4:


Here  is the  answer

**Comment by thejae** [comment]
I resolved it!!

While @bihailantian655's answer is quite a mouthful, it did set me on the right path. Here's what worked for me in Windows
```bat
# Uninstall everything
C:\ComfyUI\.venv\Scripts\python.exe -m pip uninstall  -y torch triton pytorch-triton triton-windows torchaudio torchvision

# Double check your Cuda version mine is 13.0
C:\ComfyUI\.venv\Scripts\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu130
C:\ComfyUI\.venv\Scripts\python.exe -m pip install "triton-windows<3.6"
```

**Comment by bolekcg** [comment]
Hello all .
At the very begining ....Thanks @kijai for making all those 
This thread helped me to setup comfy with above packages ... but for some reason i can't make it work 

```
MY SETUP FOR COMFY
RTX 3080Ti (laptop version)
-- NVIDIA-SMI 572.83 /Driver Version: 572.83 / CUDA Version: 12.8 /( additionally installed nvidia cuda toolkit 12.8 )
-- torch 2.9.1+cu128
-- triton-windows 3.5.1.post24
-- python 3.12.8
```

So I got rid of all those "triton_key" problems and seems like all nodes are executed but when execution enters "WanVideoSampler" node it stops saying 

> Sampling 29 frames at 832x480 with 6 steps
>   0%|                                                                                            | 0/6 [00:00<?, ?it/s]W0108 14:02:02.067000 25232 Lib\site-packages\torch\_inductor\utils.py:1613] [0/0_1] Not enough SMs to use max_autotune_gemm mode
> Error during model prediction: CUDA error: out of memory

Im using default example workflow **" wanvideo_mocha_replace_subject_kj_02"** with example files from [GITHUB_ORANGE](https://github.com/Orange-3DV-Team/MoCha/tree/main/data) 

Is that really the case of out of memory even if I'm 16GB VRAM on my 3080 ?? 
Inside attachments you can find my output and example workflow.

I would be more than gratefull if you can help me 

[LOG.txt](https://github.com/user-attachments/files/24496324/LOG.txt)

[replace.json](https://github.com/user-attachments/files/24496326/replace.json)

**Comment by kijai** [comment]
> Hello all .
> At the very begining ....Thanks @kijai for making all those 
> This thread helped me to setup comfy with above packages ... but for some reason i can't make it work 
> 
> ```
> MY SETUP FOR COMFY
> RTX 3080Ti (laptop version)
> -- NVIDIA-SMI 572.83 /Driver Version: 572.83 / CUDA Version: 12.8 /( additionally installed nvidia cuda toolkit 12.8 )
> -- torch 2.9.1+cu128
> -- triton-windows 3.5.1.post24
> -- python 3.12.8
> ```
> 
> So I got rid of all those "triton_key" problems and seems like all nodes are executed but when execution enters "WanVideoSampler" node it stops saying 
> 
> > Sampling 29 frames at 832x480 with 6 steps
> >   0%|                                                                                            | 0/6 [00:00<?, ?it/s]W0108 14:02:02.067000 25232 Lib\site-packages\torch\_inductor\utils.py:1613] [0/0_1] Not enough SMs to use max_autotune_gemm mode
> > Error during model prediction: CUDA error: out of memory
> 
> Im using default example workflow **" wanvideo_mocha_replace_subject_kj_02"** with example files from [GITHUB_ORANGE](https://github.com/Orange-3DV-Team/MoCha/tree/main/data) 
> 
> Is that really the case of out of memory even if I'm 16GB VRAM on my 3080 ?? 
> Inside attachments you can find my output and example workflow.
> 
> I would be more than gratefull if you can help me 
> 
> [LOG.txt](https://github.com/user-attachments/files/24496324/LOG.txt)
> 
> [replace.json](https://github.com/user-attachments/files/24496326/replace.json)

Out of memory is about RAM, not VRAM... So you'd need to reduce blocks swapped if possible, also if you have non-blocking enabled on the block swap node, disable that.

**Comment by bolekcg** [comment]
Thank you very much @kijai . Seems like that helped . I need to dig into what those are doing but for now i just wanted to make it work on a most simple example before starting diging further  . Great!
Thank you once again. 
All the best !!

**Comment by bolekcg** [comment]
Hello @kijai . 

I started today playing with settings and workflow itself ... but I'm kinda confused ... 
As example here [https://www.youtube.com/watch?v=SWQDyQ47giY](VideoTut) ... in the description it tells me that video is made by using 8GB VRAM... I followed exact settings from tut( again ... just to check if that's working or not ) and exact same settings don't work for me ...again ... out of memory error . 

![Image](https://github.com/user-attachments/assets/49379c4e-285c-435a-a1c3-3ff78aa494e1)

So I'm wondering why I'm not able to process the same way with even more vram.
What could be the issue ? 
Thanks in advance for any input

**Comment by kijai** [comment]
> Hello @kijai . 
> 
> I started today playing with settings and workflow itself ... but I'm kinda confused ... 
> As example here [https://www.youtube.com/watch?v=SWQDyQ47giY](VideoTut) ... in the description it tells me that video is made by using 8GB VRAM... I followed exact settings from tut( again ... just to check if that's working or not ) and exact same settings don't work for me ...again ... out of memory error . 
> 
> ![Image](https://github.com/user-attachments/assets/49379c4e-285c-435a-a1c3-3ff78aa494e1)
> 
> So I'm wondering why I'm not able to process the same way with even more vram.
> What could be the issue ? 
> Thanks in advance for any input

That's probably a RAM error, not VRAM.

**Comment by bolekcg** [comment]
@kijai Thanks for support!!
But hmm...  isnt that vram that got filled when processing ??
RAM indeed is occupied during model loading but then wanVideoSampler is doing his job ram is not fully taken . 
Maybe that's just RAM as you said but as I don't know .... i'm just asking ... ( 32 RAM is too low for this one to work ? )

Recorded process - gif below 
![Image](https://github.com/user-attachments/assets/954ad070-6b67-483f-a6b7-3de237535e4a)

Thank you once again

**Comment by bolekcg** [comment]
@kijai 
I switched comfy to --highvram and same setup is doing fine ( dedicated GPU is constantly occupied and shared RAM  is "managed" )  so I think its somehow related to managment of ram/vram and passing data between ... i just don't know exactly ...  but seems like now is working .

<img width="655" height="562" alt="Image" src="https://github.com/user-attachments/assets/87996b95-5cf2-459d-a224-bacc5609f074" />

Im just thinking now that guy from this [video tut ](https://www.youtube.com/watch?v=SWQDyQ47giY) maybe is using low vram - 8 but for sure he has a lot of RAM
