### ISSUE TITLE
WanVideoSampler AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'

### ISSUE THREAD

**Issue by LL0424** [kijai/ComfyUI-WanVideoWrapper#920]
<img width="1929" height="801" alt="Image" src="https://github.com/user-attachments/assets/ffc05625-08a2-4135-aab6-bab4611628c3" />How to solve this problem

**Comment by Klow666** [comment]
downgrade triton worked for me

**Comment by brian-personaldev** [comment]
> downgrade triton worked for me

what version downgrade to?

**Comment by brian-personaldev** [comment]
found this, I noticed my torch version is too low: Triton 3.4 only works with PyTorch >= 2.8.

**Comment by Klow666** [comment]
pip install -U "triton-windows<3.4" assuming your on torch 2.7 + if lower check the docs for correct version

**Comment by suphansli** [comment]
thx. had the same issue. downgrade worked!

**Comment by SealTecH** [comment]
> pip install -U "triton-windows<3.4" assuming your on torch 2.7 + if lower check the docs for correct version

I have torch 2.7.0+cu128  and  triton-windows 3.3.1post19 
but still got an error

**Comment by shungyuesuolong** [comment]
> > 使用pip安装 -U "triton-windows<3.4"，假设你使用的是torch 2.7 + 如果版本更低，请查看文档以获取正确版本。
> 
> 我有 torch 2.7.0+cu128 和 triton-windows 3.3.1post19 但仍然出现了一个错误

是不是fp8e4nv报错，说不支持。

**Comment by SealTecH** [comment]
> > > 使用pip安装 -U "triton-windows<3.4"，假设你使用的是torch 2.7 + 如果版本更低，请查看文档以获取正确版本。
> > 
> > 
> > 我有 torch 2.7.0+cu128 和 triton-windows 3.3.1post19 但仍然出现了一个错误
> 
> 是不是fp8e4nv报错，说不支持。

Sorry, I don't know what is fp8e4nv. And that's why I assume that no - it does not throw such error. 

My case was a bit messy. I have both Python 3.10 and 3.12 and comfy-desktop. I kept getting this error despite all the efforts to install and reinstall triton.
Then I reinstalled comfy ui in a separate folder.
 For some reason, I couldn't install triton into .venv of fresh comfy (in console it said its already installed, but in fact it was not). 
All the problems ended up when I just copied folders triton and triton-windows from 
`C:\Users\my_user\AppData\Roaming\Python\Python312\site-packages` to  .venv folder of fresh comfyUI

**Comment by addy87** [comment]
Downgrading worked for me too, thanks! For the people using ComfyUI portable:
`comfyui-portable-folder\python_embeded>python.exe -m pip install -U "triton-windows<3.4"`

**Comment by Nomad234** [comment]
> Downgrading worked for me too, thanks! For the people using ComfyUI portable: `comfyui-portable-folder\python_embeded>python.exe -m pip install -U "triton-windows<3.4"`

I've run this but still receive the same error. I doubt that triton gets properly installed in my comfyui portable, because when i run the order: python.exe -m pip uninstall triton, I receive : WARNING: Skipping triton as it is not installed.

**Comment by WuMIn259** [comment]
> > Downgrading worked for me too, thanks! For the people using ComfyUI portable: `comfyui-portable-folder\python_embeded>python.exe -m pip install -U "triton-windows<3.4"`
> 
> I've run this but still receive the same error. I doubt that triton gets properly installed in my comfyui portable, because when i run the order: python.exe -m pip uninstall triton, I receive : WARNING: Skipping triton as it is not installed.

(Drive letter)D:\ComfyUI_windows_portable\python_embeded\python.exe -m install -U "triton-windows<3.4"

One thing to note is that Triton seems to have a very different reference to the environment. Try to specify the correct address of Python when installing. If that doesn't work, try to reference the Python environment of the portable package into the system variable

**Comment by HaN3453** [comment]
Downgrading solved my problem too. I downgraded to this (3.3.1post19)

**Comment by inglob** [comment]
> Downgrading worked for me too, thanks! For the people using ComfyUI portable: `comfyui-portable-folder\python_embeded>python.exe -m pip install -U "triton-windows<3.4"`

Works form me, many thx!

**Comment by margo2130** [comment]
> downgrade triton worked for me

how i can know what version of triton i have and what version to downgrade i should choose?

**Comment by margo2130** [comment]
> > downgrade triton worked for me
> 
> what version downgrade to?

how can i downgrade my triton? can you explain how i can findout which version to downgrade?

**Comment by Alesdanz** [comment]
I tried everything I saw and nothing worked... But

I SOLVED IT with Torch 2.6 and Triton 3.2—it’s more stable.    

Step1 
pip uninstall -y torch triton triton-windows

Step2
pip install torch==2.6.0 --force-reinstall

Step3
pip install "triton-windows==3.2.0.post19" --force-reinstall

**Comment by Yogesh-DevHub** [comment]
Try disabling torch compile

**Comment by chamlyn2022** [comment]
it worked，thx

**Comment by aidifussion** [comment]
t

> pip install -U "triton-windows<3.4" assuming your on torch 2.7 + if lower check the docs for correct version

Thank it work for me..

**Comment by TwhiteShark** [comment]
brianb5010 

> 降级也对我有用，谢谢！致使用 ComfyUI 便携版的用户： `comfyui-portable-folder\python_embeded>python.exe -m pip install -U "triton-windows<3.4"`

感谢对我很有用,在此之前我问了无数次ai但是都没有解决问题。尝试了环境变量的增加修改，更新了C++编译器。cuda降级等一系列问题。我也不知道是不是在做这些前提的情况下才能降级成功的。总之很感谢您！作者这个问题可以在环境变量中增加+dynamo变量可以在ai中查到。

**Comment by InhabitancyCocoon** [comment]
> > > downgrade triton worked for me
> > 
> > 
> > what version downgrade to?
> 
> how can i downgrade my triton? can you explain how i can findout which version to downgrade?

Check [this](https://discuss.pytorch.org/t/how-to-know-which-triton-version-to-build-for-a-given-pytorch-version/206201)
