### ISSUE TITLE
AttributeError: 'WanModel' object has no attribute 'vace_patch_embedding'

### ISSUE THREAD

**Issue by ReloadProcz** [kijai/ComfyUI-WanVideoWrapper#379]
# Problem🤔
By updating to the latest version of this repository (of course the latest commit), I cannot generate any videos as before, without the so-called vace model.

# The error info from ComfyUI
```
Sampling 161 frames at 832x480 with 30 steps
  3%|███▍                                                                                                  | 1/30 [00:42<20:25, 42.26s/it]
!!! Exception during processing !!! 'WanModel' object has no attribute 'vace_patch_embedding'
Traceback (most recent call last):
  File "/home/user0/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/user0/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/user0/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/user0/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/user0/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 2623, in process
    noise_pred_context, new_teacache = predict_with_cfg(
  File "/home/user0/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 2335, in predict_with_cfg
    noise_pred_cond, teacache_state_cond = transformer(
  File "/home/user0/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user0/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user0/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 1055, in forward
    vace_hints = self.forward_vace(x, vace_context, seq_len, kwargs)
  File "/home/user0/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 852, in forward_vace
    c = [self.vace_patch_embedding(u.unsqueeze(0)) for u in vace_context]
  File "/home/user0/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 852, in <listcomp>
    c = [self.vace_patch_embedding(u.unsqueeze(0)) for u in vace_context]
  File "/home/user0/ComfyUI/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 291, in __getattr__
    return super().__getattr__(name)
  File "/home/user0/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'WanModel' object has no attribute 'vace_patch_embedding'
```
---
So how to solve this problem?

**Comment by kijai** [comment]
Are you maybe trying to use the VACE node with non-VACE model?

**Comment by ReloadProcz** [comment]
Nope, I just use the t2v long vid example workflow u gave.

**Comment by kijai** [comment]
> Nope, I just use the t2v long vid example workflow u gave.

Okay thanks, it was a bug specific to context windows without VACE, should be fixed now.

**Comment by phoenixZZZ** [comment]
I Try it，the bug seems still not fixed now
`
Sampling 81 frames at 832x480 with 25 steps
  0%|                                                                                                                                       | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/huangjunren/comfyui/master/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangjunren/comfyui/master/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangjunren/comfyui/master/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/huangjunren/comfyui/master/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangjunren/comfyui/master/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 2754, in process
    noise_pred, self.teacache_state = predict_with_cfg(
                                      ^^^^^^^^^^^^^^^^^
  File "/home/huangjunren/comfyui/master/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 2438, in predict_with_cfg
    noise_pred_cond, teacache_state_cond = transformer(
                                           ^^^^^^^^^^^^
  File "/home/huangjunren/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangjunren/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangjunren/comfyui/master/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 1064, in forward
    vace_hints = self.forward_vace(x, data["context"], seq_len, kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangjunren/comfyui/master/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/model.py", line 856, in forward_vace
    c = [self.vace_patch_embedding(u.unsqueeze(0)) for u in vace_context]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
`
I use https://github.com/kijai/ComfyUI-WanVideoWrapper/blob/main/example_workflows/wanvideo_T2V_example_02.json
not use vace-models，just use T2V

**Comment by kijai** [comment]
> I Try it，the bug seems still not fixed now

It was but I managed to break it again, it's now fixed again.

**Comment by phoenixZZZ** [comment]
> > I Try it，the bug seems still not fixed now
> 
> It was but I managed to break it again, it's now fixed again.
> 
> 

i test it，it is all right now. thank you for your fixed

**Comment by zhanglj007520** [comment]
严格使用kaijia作者对应的模型文件，其他的兼容性有问题。
https://hf-mirror.com/Kijai/WanVideo_comfy/tree/main

**Comment by Klarkingcrok** [comment]
I have an isssue triyn to add a pose control to a wan2.1 workflow, could be a basic thing, any idea?

WanVideoSampler
'WanModel' object has no attribute 'dwpose_embedding'

**Comment by helto4real** [comment]
Actually get this error again now. Tried the Ditto official model with version 3.1.7

**Comment by kijai** [comment]
> Actually get this error again now. Tried the Ditto official model with version 3.1.7

The model or the Lora? They have loras for vace and then full vace separately, so you either use the full one as vace module (the 6gb file) or you just use vace normally and load the Lora, result wise it's pretty much same.

**Comment by helto4real** [comment]
> > Actually get this error again now. Tried the Ditto official model with version 3.1.7
> 
> The model or the Lora? They have loras for vace and then full vace separately, so you either use the full one as vace module (the 6gb file) or you just use vace normally and load the Lora, result wise it's pretty much same.

Thanks for replying. Added the part of the workflow here.  This is the workflow I am using: https://github.com/EzioBy/Ditto/blob/main/ditto_comfyui_workflow.json, 

<img width="1711" height="1526" alt="Image" src="https://github.com/user-attachments/assets/62a28a91-b8a2-415c-b732-ca20601634ba" />

**Comment by phaserblast** [comment]
**EDIT: Fixed, see solution below.**

Just updated the nodes, and this is broken for me too. Same error from WanVideo Sampler: 'WanModel' object has no attribute 'vace_patch_embedding'

Output from main.py:
AttributeError: 'WanModel' object has no attribute 'vace_patch_embedding'. Did you mean: 'pose_patch_embedding'?

**Comment by yongshaochen** [comment]
i have the same problem,should use 6 g or the 245 M file,there are 2 file?

**Comment by yongshaochen** [comment]
<img width="1369" height="1021" alt="Image" src="https://github.com/user-attachments/assets/fa8acaa2-ffa2-48a3-9bf7-09edc3b7b69d" />

**Comment by phaserblast** [comment]
Yup, you beat me to it!
You need the VACE module AND the LoRA, or the combined VACE/LoRA. You can download all this stuff from https://huggingface.co/Kijai/WanVideo_comfy/tree/main

This also works using the vanilla 2.1 VACE module:

<img width="1253" height="638" alt="Image" src="https://github.com/user-attachments/assets/ea1e53a8-dbf9-4ebf-879f-680103e251b4" />
